[package]
name = "project_euler_problems"
version = "0.1.0"
authors = ["Anand Krishna <anandkrishna2312@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
